void _print_rev_recursion(char *s);
void _puts_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int _putchar(char c);
int square(int m, int k);
int isit_prime(int i, int m);
void putsrecursion(int i, int n, char *s);
void print_rev_recursion(int i, int n, char *s);
